### ISSUE TITLE
在OpenKylin 1.0桌面环境下无法运行

### ISSUE THREAD

**Issue by 5653325** [raokun/TerraMours.Chat.Ava#11]
已安装.net7.0环境，拉下代码后发布为linux-x64，把文件复制到OpenKylin的下载目录下，执行dotnet TerraMours.Chat.Ava.dll，提示如下错误：
![image](https://github.com/raokun/TerraMours.Chat.Ava/assets/3361135/e0820d19-e7dc-4b37-943d-532b0bd34917)
操作系统版本：
![image](https://github.com/raokun/TerraMours.Chat.Ava/assets/3361135/c0266b92-0d4c-4078-9147-f0c76ca60af2)

**Comment by raokun** [comment]
你可以看看我的踩坑博客，你遇到的问题我有记录[https://www.raokun.top/archives/avalonia-xiang-mu-zai-openkylin-yun-xing-cai-keng](https://www.raokun.top/archives/avalonia-xiang-mu-zai-openkylin-yun-xing-cai-keng)

**Comment by raokun** [comment]
在openkylin中运行需要把语言换成英文
![image](https://github.com/raokun/TerraMours.Chat.Ava/assets/43564692/0564f887-46a5-4b50-91bb-22a6c9d64292)

**Comment by 5653325** [comment]
谢谢大佬，语言切换成英文没问题。
有没有不切换语言，可以运行的办法？毕竟这个系统下使用的环境绝大部分都是需要简体中文。

另外就是踩坑经验那篇文中中的“代码中修改掉linux不支持的字体”这部分，那些字体是不是放在App.axml中的
<FontFamily x:Key="diyFont">这里放字体名称</FontFamily>
这个配置里，是不是就是全局启用了？

**Comment by raokun** [comment]
我没有更深入的研究了，没找到其他的实现方案。也可以等等Avalonia与 openkylin 开源社区共建，后续应该会越来越好。
字体可以全局搜索下“FontFamily”，app中配置的是全局的。也可以在独立页面axaml中单独配置

**Comment by 5653325** [comment]
好的。谢谢大佬。
